# Generated by Django 3.2.12 on 2022-03-31 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userno', models.AutoField(primary_key=True, serialize=False)),
                ('userfirstname', models.CharField(max_length=20)),
                ('usermiddlename', models.CharField(blank=True, max_length=20, null=True)),
                ('userlastname', models.CharField(max_length=20)),
                ('usernickname', models.CharField(max_length=20, unique=True)),
                ('useremail', models.CharField(max_length=30)),
                ('usergender', models.CharField(max_length=10)),
                ('userpwd', models.CharField(max_length=30)),
                ('userdob', models.DateField()),
                ('usernote1', models.IntegerField(blank=True, null=True)),
                ('usernote2', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Userloginactivityrecords',
            fields=[
                ('actno', models.AutoField(primary_key=True, serialize=False)),
                ('acttime', models.DateTimeField()),
                ('acttype', models.CharField(blank=True, max_length=30, null=True)),
                ('userno', models.ForeignKey(db_column='userno', on_delete=django.db.models.deletion.DO_NOTHING, to='apptasklistmng.users')),
            ],
            options={
                'db_table': 'UserLoginActivityRecords',
            },
        ),
        migrations.CreateModel(
            name='Userchangerecords',
            fields=[
                ('chgno', models.AutoField(primary_key=True, serialize=False)),
                ('chgtime', models.DateTimeField()),
                ('chgentry', models.CharField(blank=True, max_length=30, null=True)),
                ('chgbefore', models.CharField(blank=True, max_length=100, null=True)),
                ('chgafter', models.CharField(blank=True, max_length=100, null=True)),
                ('chgpwd', models.CharField(blank=True, max_length=30, null=True)),
                ('chgpwdbefore', models.CharField(blank=True, max_length=30, null=True)),
                ('chgpwdafter', models.CharField(blank=True, max_length=30, null=True)),
                ('userno', models.ForeignKey(db_column='userno', on_delete=django.db.models.deletion.DO_NOTHING, to='apptasklistmng.users')),
            ],
            options={
                'db_table': 'UserChangeRecords',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('taskno', models.AutoField(primary_key=True, serialize=False)),
                ('taskcontext', models.CharField(max_length=100)),
                ('taskddl', models.DateField(blank=True, null=True)),
                ('taskorder', models.IntegerField()),
                ('taskimportant', models.IntegerField()),
                ('taskisfinished', models.IntegerField()),
                ('userno', models.ForeignKey(db_column='userno', on_delete=django.db.models.deletion.DO_NOTHING, to='apptasklistmng.users')),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
    ]
